version: '3.9'

services:
  order-app:
    build: . 
    image: order:v1.0.0
    container_name: order-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vegetable_order_app
    depends_on:
      - mongodb
    networks:
      - rithika-network


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - rithika-network

networks:
  rithika-network:
    driver: bridge

