apiVersion: v1
kind: Service
metadata:
  name: vegetable-order-app-service
  namespace: rithika-ns
spec:
  selector:
    app: vegetable-order-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: LoadBalancer