apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  serviceName: {{ .Values.statefulset.serviceName }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.labels.app }}
    spec:
      containers:
      - name: {{ .Values.statefulset.containers.name }}
        image: ""{{ .Values.mongodb.repository }}:{{ .Values.mongodb.tag }}""
        ports:
        - containerPort: {{ .Values.statefulset.containers.port }}
        volumeMounts:
          - mountPath: {{ .Values.statefulset.containers.volumeMounts.mountPath }}
            name: {{ .Values.statefulset.containers.volumeMounts.name }}
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: MONGO_INITDB_DATABASE

  volumeClaimTemplates:  # it is referencing pvc automatically instead of refering pvc manually in the pod or yaml file
    - metadata:
        name: {{ .Values.statefulset.volumeMounts.name }}
      spec:
        accessModes: {{ .Values.statefulset.volumeMounts.accessModes }}
        storageClassName: {{ .Values.statefulset.volumeMounts.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.statefulset.volumeMounts.storage }}
