apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.mongodb.app }}
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
