apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodbservice
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.mongodbService.app }}
  ports:
    - port: {{ .Values.mongodbService.port }}
      targetPort: {{ .Values.mongodbService.port }}
      protocol: {{ .Values.mongodbService.protocol }}
  clusterIP: {{ .Values.mongodbService.clusterIP }}
