apiVersion: v1
kind: ConfigMap
metadata:
  name: vegetable-app-config
  namespace: rithika-ns
data:
<<<<<<< HEAD
  MONGO_URL: "mongodb://mongodb:27017/vegetable_order_app"
=======
  MONGO_URI: "mongodb://mongodb:27017/vegetable_order_app"
>>>>>>> origin/main
  MONGO_INITDB_DATABASE: "vegetable_order_app"
